#!/bin/bash
# Find a working census stream

MAX_STREAM=50
DEBUG=0

function do_sleep {
    sleep $(($RANDOM%30))
}

function report_domain {
    if [ $DEBUG -eq 1 ];
    then
        echo "Domain $1 is invalid. Try tweaking the stream params."
    fi
}

while [ 1 ];
do
    stream=$(($RANDOM%$MAX_STREAM))

    if [ $stream -lt 10 ];
    then
        stream="0${stream}"
    fi

    domain="stream${stream}.census.abs.gov.au"
    domain_valid=$(dig +short $domain)

    if [ $? -ne 0 ];
    then
        report_domain $domain
        do_sleep
        continue
    else
        if [ -z "$domain_valid" ];
        then
            report_domain $domain
            do_sleep
            continue
        fi
    fi

    url="https://${domain}/eCensusWeb/login.jsp"
    res=$(curl -sS \
       -H "Referer: https://${domain}/eCensusWeb/welcome.jsp" \
       -d 'vf=1' \
       -d 'pcsf=true' \
       -d "vipUrl=https://${domain}" \
       -d 'primaryStreamNumber=1' \
       -d 'primaryServerNumber=1' \
       -d "primaryUrl=https://${domain}" \
       -d "currentUrl=https://${domain}" \
       ${url})

    error=$(echo $res | grep 'The system is very busy at the moment.')

    if [ $DEBUG -eq 1 ];
    then
        echo "Page result"
        echo "$res"
    fi

    if [ -z "$error" ];
    then
        echo "Stream ${stream} is working!"
        echo "Try HTTP POST to ${url}"
        exit 0
    fi

    do_sleep;
done
